apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cla-backend.fullname" . }}-metabase
spec:
  replicas: 1 # Metabase does not support horizontal scaling.
  selector:
    matchLabels:
      app: {{ include "cla-backend.fullname" . }}-metabase
  template:
    metadata:
      labels:
        app: {{ include "cla-backend.fullname" . }}-metabase
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cla-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: metabase
        image: metabase/metabase:latest
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 3000
        resources:
          requests:
            cpu: 25m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 3Gi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 10000
          runAsGroup: 10000
        env:
          - name: MB_DB_CONNECTION_URI
            valueFrom:
              secretKeyRef:
                name: metabase
                key: jdbc_url