{{- if .Values.ingress.enabled -}}
{{- if .Values.metabase.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "laa-govuk-notify-orchestrator.fullname" . }}-app
  labels:
    {{- include "cla-backend.labels" . | nindent 4 }}
  namespace: {{.Release.Namespace}}
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "{{ $ingressName }}-{{ .Release.Namespace }}-{{- .Values.ingress.cluster.name -}}"
    external-dns.alpha.kubernetes.io/aws-weight: "{{- .Values.ingress.cluster.weight -}}"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  tls:
  - hosts:
      - "cla-dashboard-{{ .Values.environment }}.cloud-platform.service.justice.gov.uk"
  rules:
  - host: "cla-dashboard-{{ .Values.environment }}.cloud-platform.service.justice.gov.uk"
    http:
    paths:
        - path: "/"
        pathType: ImplementationSpecific
        backend:
            service:
            name: {{ $fullName }}-metabase
            port:
                number: 80
{{- end }}
{{- end }}