#!/bin/sh -e
NAMESPACE=$1

# These variables are required in multiple places such as
# tag_and_push_docker_image as well as the bin/<NAMESPACE>_deploy.sh scripts
export DOCKER_REPOSITORY="$ECR_DOCKER_REPOSITORY"
export safe_git_branch=${CIRCLE_BRANCH//\//-}
export short_sha="$(git rev-parse --short=7 $CIRCLE_SHA1)"
export IMAGE_TAG="$safe_git_branch.$short_sha"
export ECR_DEPLOY_IMAGE="$DOCKER_REPOSITORY/$IMAGE_TAG"

case $NAMESPACE in
  production)
      export NAMESPACE_HOST="${PRODUCTION_HOST}"
      ;;
  uat)
      export NAMESPACE_HOST="${UAT_HOST}"
      ;;
  staging)
      export NAMESPACE_HOST="${STAGING_HOST}"
      ;;
  training)
      export NAMESPACE_HOST="${TRAINING_HOST}"
      ;;
  *)
      return
      ;;
esac

export CLEANED_BRANCH_NAME=$(echo $CIRCLE_BRANCH | sed 's/^feature[-/]//' | sed 's:^\w*\/::' | tr -s ' _/[]().' '-' | tr '[:upper:]' '[:lower:]' | cut -c1-28 | sed 's/-$//')
if [ $NAMESPACE == "uat" ]; then
  export RELEASE_NAME=${CLEANED_BRANCH_NAME}
  export RELEASE_HOST=${RELEASE_NAME}-${NAMESPACE_HOST}
else
  export RELEASE_NAME=cla-backend
  export RELEASE_HOST=${NAMESPACE_HOST}
fi
