#!/bin/sh -e
NAMESPACE=$1
DYNAMIC_HOSTNAME=$2

# These variables are required in multiple places such as
# the bin/<NAMESPACE>_deploy.sh scripts
export DOCKER_REPOSITORY="$ECR_DOCKER_REPOSITORY"
export safe_git_branch=${CIRCLE_BRANCH//\//-}
export CLEANED_BRANCH_NAME=$(echo $CIRCLE_BRANCH | sed 's/^feature[-/]//' | sed 's:^\w*\/::' | tr -s ' _/[]().' '-' | tr '[:upper:]' '[:lower:]' | cut -c1-28 | sed 's/-$//')
export short_sha="$(git rev-parse --short=7 $CIRCLE_SHA1)"
export IMAGE_TAG="$CLEANED_BRANCH_NAME.$short_sha"
export ECR_DEPLOY_IMAGE="$DOCKER_REPOSITORY:$IMAGE_TAG"

build_beta_release_host() {
  service_name=${1%%.*}
  printf '%s.beta.cloud-platform.service.justice.gov.uk' "$service_name"
}

if [ "$DYNAMIC_HOSTNAME" = true ]; then
  export RELEASE_NAME=${CLEANED_BRANCH_NAME}
  export RELEASE_HOST=${RELEASE_NAME}-${HOST}
else
  export RELEASE_NAME=cla-backend
  export RELEASE_HOST=${HOST}
fi

if [ -n "$NAMESPACE" ] && [ "$NAMESPACE" != "production" ]; then
  export RELEASE_HOST=$(build_beta_release_host "$RELEASE_HOST")
fi

if [ "$CIRCLE_BRANCH" == "main" ]; then
  export TARGET_TAGS=$IMAGE_TAG,$CLEANED_BRANCH_NAME,"latest"
else
  export TARGET_TAGS=$IMAGE_TAG,$CLEANED_BRANCH_NAME
fi
