#!/bin/sh -e

source $(dirname "$0")/define_build_environment_variables
built_tag="$1"

function tag_and_push() {
  tag="$1"
  echo
  echo "Tagging and pushing $tag..."
  docker tag $built_tag $tag
  docker push $tag
}

tag_and_push "$ECR_DOCKER_REPOSITORY:$CLEANED_BRANCH_NAME.$short_sha"
tag_and_push "$ECR_DOCKER_REPOSITORY:$CLEANED_BRANCH_NAME"

if [ "$CIRCLE_BRANCH" == "master" ]; then
  tag_and_push "$ECR_DOCKER_REPOSITORY:latest"
fi
