#!/bin/sh -e

source $(dirname "$0")/define_build_environment_variables
built_tag="$1"

function tag_and_push() {
  tag="$1"
  echo
  echo "Tagging and pushing $tag..."
  docker tag $built_tag $tag
  docker push $tag
}

function tag_and_push_database_migration() {
  tag="$ECR_DOCKER_REPOSITORY:database-migration"
  echo
  echo "Tagging and pushing $tag..."
  docker tag database-migration $tag
  docker push $tag
}

function tag_and_push_canary_deployment() {
  tag_and_push "$CANARY_ECR_DEPLOY_IMAGE"
}

function tag_and_push_app_deployment() {
    tag_and_push "$ECR_DEPLOY_IMAGE"
    tag_and_push "$ECR_DEPLOY_IMAGE_NO_SHA"
    tag_and_push_database_migration
    if [ "$CIRCLE_BRANCH" == "master" ]; then
    tag_and_push "$ECR_DOCKER_REPOSITORY:latest"
  fi
}

if [ $IS_CANARY_DEPLOYMENT = true ]; then
  tag_and_push_canary_deployment
else
  tag_and_push_app_deployment
fi
