# Default values for cla-backend in a dev environment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
environment: "uat"
image:
  pullPolicy: IfNotPresent

replicaCount: 1

localPostgres:
  enabled: false

queueWorkers:
  enabled: false

ingress:
  enabled: true
  whitelist_additional:
    - 52.210.85.116/32

# Lists don't deep merge, so this list of envVars overrides anything defined in an earlier values file
envVars:
  DEBUG:
    value: "False"
  DB_HOST:
    secret:
      name: eligibility-integration-database-14
      key: host
  DB_PORT:
    secret:
      name: eligibility-integration-database-14
      key: port
      optional: true
  DB_NAME:
    secret:
      name: eligibility-integration-database-14
      key: name
  DB_USER:
    secret:
      name: eligibility-integration-database-14
      key: user
  DB_PASSWORD:
    secret:
      name: eligibility-integration-database-14
      key: password
  REPLICA_DB_HOST:
    secret:
      optional: true
  LOAD_SEED_DATA:
    value: "True"
  LOAD_TEST_DATA:
    value: "True"
  LOAD_END_TO_END_FIXTURES:
    value: "False"
  SQS_ACCESS_KEY:
    value: "False"
  SQS_SECRET_KEY:
    value: "False"
  FRONTEND_HOST_NAME:
    value: "laa-cla-frontend-uat.apps.live-1.cloud-platform.service.justice.gov.uk"
  EXPRESS_SERVER_HOST:
    value: "http://cla-frontend-socket-server.laa-cla-frontend-uat.svc.cluster.local"
  MIGRATE_OAUTH_DATA:
    value: "False"
