name: Snyk Image Scan

on:
  workflow_run:
    workflows: ["workflow.yml"]
    types:
      - completed

permissions:
  contents: read

jobs:
  snyk-image-scan:
    name: Snyk Image Scan
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Debug trigger
        run: echo "Testing that this waits before running"