name: Build, Push and Snyk Scan

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          role-to-assume: ${{ secrets.CLA_BACKEND_ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.CLA_BACKEND_ECR_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@261fc3d4806db1fa66a15cc11113c456db8870a7 # v2.1.0
        with:
          mask-password: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6.0.0
        with:
          images: ${{ steps.login-ecr.outputs.registry }}/${{ vars.CLA_BACKEND_ECR_REPOSITORY }}
          tags: |
            type=raw,value=${{ github.ref_name == 'main' && format('main-{0}', github.sha) || format('branch-{0}', github.sha) }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: production

  snyk-image-scan:
    name: Snyk Image Scan
    needs: build-and-push
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Run Snyk scan workflow
        uses: ministryofjustice/laa-reusable-github-actions/.github/workflows/sast.yml@a652d1076b05dd80d3ab619d263aac6ce526d70b
        with:
          image_uri: ${{ needs.build-and-push.outputs.image_tag }}
          dockerfile_path: Dockerfile
        secrets:
          SNYK_CLIENT_ID: ${{ secrets.SNYK_CLIENT_ID }}
          SNYK_CLIENT_SECRET: ${{ secrets.SNYK_CLIENT_SECRET }}
          ECR_ROLE_TO_ASSUME: ${{ secrets.CLA_BACKEND_ECR_ROLE_TO_ASSUME }}