{{- if .Values.certificate.create -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "cla-backend.fullname" . }}-cert
  namespace: laa-fala-staging
spec:
  secretName: {{ include "cla-backend.fullname" . }}-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "{{ .Values.host }}"
  acme:
    config:
    - domains:
      - "{{ .Values.host }}"
      dns01:
        provider: route53-cloud-platform
{{- end }}
