apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-house-keeping
  labels:
    {{- include "cla-backend.labels" . | nindent 4 }}
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          containers:
          - name: housekeeping
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["python", "manage.py", "housekeeping"]
            env:
              {{ include "cla-backend.app.vars" . | nindent 12 }}
          serviceAccountName: {{ include "cla-backend.serviceAccountName" . }}
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-missing-codes
  labels:
    {{- include "cla-backend.labels" . | nindent 4 }}
spec:
  schedule: "15 2 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          containers:
          - name: run-command
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["python", "manage.py", "monitor_missing_outcome_codes"]
            env:
              {{ include "cla-backend.app.vars" . | nindent 12 }}
          serviceAccountName: {{ include "cla-backend.serviceAccountName" . }}
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-mi-cb1-report
  labels:
    {{- include "cla-backend.labels" . | nindent 4 }}
spec:
  schedule: "0 5 * * 0"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          containers:
          - name: reporting
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["python", "manage.py", "mi_cb1_report"]
            env:
              {{ include "cla-backend.app.vars" . | nindent 12 }}
          serviceAccountName: {{ include "cla-backend.serviceAccountName" . }}
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-delete-unused-cases
  labels:
    {{- include "cla-backend.labels" . | nindent 4 }}
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          containers:
          - name: delete-unused-cases
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["python", "manage.py", "delete_cases_without_personal_data"]
            env:
              {{ include "cla-backend.app.vars" . | nindent 12 }}
          serviceAccountName: {{ include "cla-backend.serviceAccountName" . }}
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-fix-outcome-codes
  labels:
    {{- include "cla-backend.labels" . | nindent 4 }}
spec:
  schedule: "0 5 3 * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          containers:
          - name: fix-missing-outcome-codes
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["python", "manage.py", "fix_missing_outcome_codes"]
            env:
              {{ include "cla-backend.app.vars" . | nindent 12 }}
          serviceAccountName: {{ include "cla-backend.serviceAccountName" . }}
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-remove-expired-reports
  labels:
    {{- include "cla-backend.labels" . | nindent 4 }}
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          containers:
          - name: remove-expired-reports
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: ["python", "manage.py", "remove_expired_reports"]
            env:
              {{ include "cla-backend.app.vars" . | nindent 12 }}
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
          serviceAccountName: {{ include "cla-backend.serviceAccountName" . }}
          restartPolicy: OnFailure

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-hourly-snapshots
  labels:
    {{- include "cla-backend.labels" . | nindent 4 }}

spec:
  schedule: "0 * * * *"

  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 7200
      template:
        spec:
          serviceAccountName: {{ include "cla-backend.serviceAccountName" . }}
          restartPolicy: OnFailure

          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000

          containers:
            - name: hourly-snapshots
              image: "{{ .Values.image.repository }}:awscli-v1"
              command:
                - /bin/sh
                - /app/automate_backup.sh

              env:
                {{- include "cla-backend.app.vars" . | nindent 16 }}

              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL


---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-delete-hourly-snapshots
  labels:
    {{- include "cla-backend.labels" . | nindent 4 }}
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 7200
      template:
        spec:
         securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
        containers:
          - name: delete-hourly-snapshots
            image:  "{{ .Values.image.repository }}:awscli:latest-v1"
            command: ["sh", "/app/automate_database_delete.sh"]
            securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            env:
              {{ include "cla-backend.app.vars" . | nindent 12 }}
            serviceAccountName: {{ include "cla-backend.serviceAccountName" . }}
            restartPolicy: OnFailure
