{{- if .Values.ingress.enabled -}}
{{- $fullName := include "cla-backend.fullname" . -}}
{{- $ingressName := printf "%s-%s" $fullName "v122" -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $ingressName }}
  labels:
    {{- include "cla-backend.labels" . | nindent 4 }}
  annotations:
# Add annotation to exclude 503 error pages from the list the cloud-platform error pages
# and use our error pages for 503 errors
    nginx.ingress.kubernetes.io/custom-http-errors: "413,502,504"
    {{- if .Values.ingress.cluster.name }}
    external-dns.alpha.kubernetes.io/set-identifier: "{{ $ingressName }}-{{ .Release.Namespace }}-{{- .Values.ingress.cluster.name -}}"
    external-dns.alpha.kubernetes.io/aws-weight: "{{- .Values.ingress.cluster.weight -}}"
    {{- end }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ include "cla-backend.whitelist" . }}"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
spec:
  ingressClassName: "modsec"
  tls:
    - hosts:
       - "{{ .Values.host }}"
      {{- if .Values.secretName }}
      secretName: {{ .Values.secretName }}
      {{- end }}
    {{- if .Values.metabase.enabled }}
    - hosts:
       - "cla-dashboard-{{ .Values.environment }}.apps.live.cloud-platform.service.justice.gov.uk"
    {{- end }}
  rules:
    - host: "{{ .Values.host }}"
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-app
                port:
                  number: {{ $svcPort }}
    {{- if .Values.metabase.enabled }}
    - host: "cla-dashboard-{{ .Values.environment }}.apps.live.cloud-platform.service.justice.gov.uk"
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-metabase
                port:
                  number: 80
    {{- end}}
{{- end }}
